#!/bin/bash

echo
echo with failure
echo

echo 'echo hi
bash -c "echo -n zerooooooo ; sleep 2 ; echo hiiiii ; exit 0"
bash -c "echo one23 ; sleep 1 ; echo whaaaaat 1>&2 ; exit 123"
echo done' | ./parallel

echo
echo with only success
echo

echo 'echo hi
bash -c "echo -n zerooooooo ; sleep 2 ; echo hiiiii ; exit 0"
bash -c "echo one23 ; sleep 1 ; echo whaaaaat 1>&2"
echo done' | ./parallel

echo
echo should have 4 lines as it fixed newline
echo

echo -n 'echo one
echo two
echo three
echo four' | ./parallel


echo
echo with 4 lines, 2 blank
echo

echo 'echo hi


echo done' | ./parallel
